# Site settings
title:          Depth First Learning
email: depthfirstlearning@gmail.com
description:    "Machine Learning Curricula"
url:            "https://www.depthfirstlearning.com"
twitter_username: depthfirstlearning
github_username:  deconstructed

# Authors
dfl:
    name: Depth First Learning
    email: depthfirstlearning@gmail.com
    web: http://twitter.com/depthfirstlearning
avital:
    name: Avital Oliver
    email: avitalo@google.com
    web: http://twitter.com/avitaloliver
cinjon:
    name: Cinjon Resnick
    email: cinjon.resnick@gmail.com
    web: http://twitter.com/cinjoncin
surya:
    name: Surya Bhupatiraju
    email: sbhupatiraju@google.com
    web: http://twitter.com/suryabhupa

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
